### ISSUE TITLE
Missing file https://github.com/microsoft/Olive/blob/main/docs/source/overview/configuring_pass

### ISSUE THREAD

**Issue by acube3** [microsoft/Olive#866] opened 2024-01-09 22:02 UTC
**Describe the bug**
https://github.com/microsoft/Olive/blob/main/docs/source/overview/configuring_pass is missing which is referenced in https://github.com/microsoft/Olive/blob/main/docs/source/overview/options.md#passes-information

**To Reproduce**
Visit https://github.com/microsoft/Olive/blob/main/docs/source/overview/options.md#passes-information and click on <configuring pass> link on the line "Please refer to [Configuring Pass](https://github.com/microsoft/Olive/blob/main/docs/source/overview/configuring_pass) for more details on type, disable_search and config."

**Expected behavior**
(https://github.com/microsoft/Olive/blob/main/docs/source/overview/configuring_pass) should open

**Olive config**
Add Olive configurations here.

**Olive logs**
Add logs here.

**Other information**
 - OS: [e.g. Windows, Linux]
 - Olive version: [e.g. 0.4.0 or main]
 - ONNXRuntime package and version: [e.g. onnxruntime-gpu: 1.16.1]

**Additional context**

**Comment by guotuofeng** [comment] 2024-01-10 01:19
Thanks for reporting this. the issue should be fixed in the linked PR.

**Comment by guotuofeng** [comment] 2024-01-10 02:43
the issue is fixed.

**Closed by guotuofeng** 2024-01-10 02:43 UTC
