### ISSUE TITLE
[FR]: Whisper int4 support

### ISSUE THREAD

**Issue by ningpengtao-coder** [microsoft/Olive#678] opened 2023-11-01 02:59 UTC
### Proposal Summary

intel int4 quantization
https://huggingface.co/Intel/whisper-large-onnx-int4

Intel supports whisper int4 quantization using the MatMulFpQ4 operator of onnxruntime 1.16.0, and I saw that llama supports using OnnxMatMul4Quantizer to complete int4 quantization. Can whisper also support OnnxMatMul4Quantizer to complete int4 quantization?

### What component(s) does this request affect?

- [X] OliveModels
- [X] OliveSystems
- [X] OliveEvaluator
- [X] Metrics
- [X] Engine
- [X] Passes
- [X] Other

**Comment by trajepl** [comment] 2023-11-15 08:57
![image](https://github.com/microsoft/Olive/assets/13343117/09943656-8762-42ab-8e20-b583827959a1)

I did not compare the latency with fp32/fp16, but the int4 should work for olive whisper example, you can just change the int8 dynamic quantization as above config.

**Comment by ningpengtao-coder** [comment] 2023-11-16 06:22
@trajepl Thanks I will try it later

**Comment by DimQ1** [comment] 2023-12-18 07:24
Hey it works with a really great result. [Whisper-int4](https://huggingface.co/DzmitryShchamialiou)

**Comment by DimQ1** [comment] 2023-12-19 06:23
Hey. I made rud test
Driver Description:          NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Video Memory:                6144 MBytes of GDDR6 SDRAM [Micron]

[1272-141231-0002.mp3](https://github.com/DimQ1/Whisper-HybridLoop-Onnx-Demo/blob/shdmitry/performance-test/AudioNoteTranscription/AudioFiles/1272-141231-0002.mp3)
File duration                                   : 13s 428ms

whisper-large-v2-int8 
Transcribe duration avg			: 16s 713ms
**realtime ratio 0.803458437**

whisper-large-v2-int4
Transcribe duration avg 			: 2s 963ms

**faster in 5.640482619 times**
**realtime ratio 4.531893351**

I tested in [C# demo app](https://github.com/DimQ1/Whisper-HybridLoop-Onnx-Demo/tree/shdmitry/performance-test)

**Comment by trajepl** [comment] 2023-12-19 10:48
Wow, great to see this big improvements!

**Comment by ningpengtao-coder** [comment] 2023-12-21 13:29
A simple experiment:
model: whisper-medium
experiment: 15s audio running 10 times.

device	bit  running time  cpu core/gpu util	memory
cpu 	int8 45s 	   i9 24 core 		4.1G
cpu 	int4 63s 	   i9 24 core 		2.9G
gpu 	int8 57s 	   4090 39%     	2.7G
gpu 	int4 7s  	   4090 80~90%     	3.8G

in conclusion:

Running int4 on the CPU seems to be limited by the CPU processing speed, resulting in 40% slower than int8 and 1G less memory.
Int4 on the GPU runs 7 to 8 times faster than int8. At the same time, the computing resource usage is close to 100%. The memory has increased by 1G. Int8 cannot fully utilize the performance of 4090.
Overall, Int4 should be faster but requires more computing resources.

**Comment by ningpengtao-coder** [comment] 2023-12-21 15:47
I ran the inference of the original model (GPU) through the following command. The speed of audio inference for 5 minutes is similar to that of int4 onnx (GPU), and the memory usage is about twice as much. Is there any problem with the int8 onnx model (GPU) that prevents full use of gpu resources?
gpu inference (4090 utilization 90%):
time whisper 1.wav --language zh --model medium

real 0m28.003s
user 0m40.866s
sys 0m3.852s

**Comment by trajepl** [comment] 2023-12-22 00:39
Thanks for the comparison! Currently, the int8 is not supported very well in onnxruntime gpu. But fortunately, the supporting is coming.

I do not know the detailed reason whey int8 does not fully utilize the gpu memory. But I suppose it might be caused by some operations(quantization) are not optimized in gpu.

Also, we have similar experiences before, that leads following convention:
1. For gpu, int4, fp16 are better, and avoid apply int8 quantization as of now.
2. For cpu, avoid fp16. For int4 there are several passes to get the int4 model, we need to search for better performance.

**Comment by ningpengtao-coder** [comment] 2023-12-22 03:19
"blockwise_quant_int4":{
		"type": "OnnxMatMul4Quantizer",
		"disable_search": true
},

"bnb_quantization": {
	"type": "OnnxBnb4Quantization",
	"config": {
		"quant_type": "nf4",
		"save_as_external_data": true,
		"all_tensors_to_one_file": true
	}
},

bnb_quantization fp4 has better performance than nf4 and blockwise_quant_int4. Compared with blockwise_quant_int4, the performance is improved by 40%.

15s audio running 50 times.
bit | model size | running time | running memory | gpu util
-- | -- | -- | -- | --
fp4 | 636M | 22s | 3.62G | 95%
nf4 | 636M | 24s | 3.67G | 95%
int4 | 681M | 34s | 36.4G | 85%~95%

**Comment by trajepl** [comment] 2023-12-22 03:44
Excellent! Will try to add the official example in Olive later.

**Comment by ningpengtao-coder** [comment] 2023-12-28 05:43
The whisper variants I currently use include faster-whisper, whisper.cpp, and olive-whisper. If sorted by inference speed (gpu nvidia 4090), these three are almost the same. If sorted by memory usage (from small to large), faster-whisper->whisper.cpp->olive-whisper.
The memory footprint of whisper.cpp or faster-whisper is half that of olive-whisper.
Is there a way to optimize the memory footprint of olive-whisper?

I prefer using the onnx model and don't want to give up the olive whisper model.

**Comment by trajepl** [comment] 2024-01-04 06:43
I have no idea about how to optimize memory footprint.
It might not be a fair comparison? The factors like input data size, batch size, or memory cache may affect the memory footprint.

**Comment by jambayk** [comment] 2024-04-10 13:48
Closing issue since int4 quantization is already supported.

Memory footprint is out of scope for Olive and handled my onnxruntime https://github.com/microsoft/onnxruntime.
There have been multiple int4 improvements made in ORT so it might have already been addressed by them.

**Closed by jambayk** 2024-04-10 13:48 UTC
Labels: enhancement

**Comment by MrRace** [comment] 2024-07-03 10:01
@jambayk  Can you provide a complete example of int4 at https://github.com/microsoft/Olive/tree/main/examples/whisper ? I tried to quantize whisper-tiny with int4 myself, but the ASR results were not satisfactory with some wrong. The core configuration is as follows:
```
"blockwise_quant_int4": {
"type": "OnnxMatMul4Quantizer",
"disable_search": true
}"
```
