### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'olive'

### ISSUE THREAD

**Issue by robgw84** [microsoft/Olive#754] opened 2023-11-25 05:03 UTC
### What happened?

I was trying to follow the steps to set up Olive as shown here https://community.amd.com/t5/ai/how-to-running-optimized-automatic1111-stable-diffusion-webui-on/ba-p/625585 but using the main branch instead of the one mentioned there, but when it gets to the step to optimize a model it is now saying:

Traceback (most recent call last):
  File "G:\Program Files (x86)\Stable-diffusion-webui-Olive\Olive\examples\directml\stable_diffusion\stable_diffusion.py", line 23, in <module>
    from olive.model import ONNXModel
ModuleNotFoundError: No module named 'olive'

### Version?

The current newest version as of Nov 24th

**Comment by guotuofeng** [comment] 2023-11-26 02:12
what's your pip list result?

**Comment by robgw84** [comment] 2023-11-26 04:01
> what's your pip list result?

`alembic                 1.12.1
archspec                0.2.1
boltons                 23.0.0
Brotli                  1.0.9
certifi                 2023.7.22
cffi                    1.15.1
charset-normalizer      2.0.4
colorama                0.4.6
colorlog                6.7.0
conda                   23.10.0
conda-content-trust     0.2.0
conda-libmamba-solver   23.11.1
conda-package-handling  2.2.0
conda_package_streaming 0.9.0
cryptography            41.0.3
filelock                3.13.1
fsspec                  2023.10.0
greenlet                3.0.1
huggingface-hub         0.19.4
idna                    3.4
install                 1.3.5
Jinja2                  3.1.2
jsonpatch               1.32
jsonpointer             2.1
libmambapy              1.5.3
Mako                    1.3.0
MarkupSafe              2.1.3
menuinst                1.4.19
mpmath                  1.3.0
networkx                3.2.1
numpy                   1.26.2
olive-ai                0.5.0
onnx                    1.15.0
optuna                  3.4.0
packaging               23.1
pandas                  2.1.3
pip                     23.3
pluggy                  1.0.0
protobuf                3.20.3
pycosat                 0.6.6
pycparser               2.21
pydantic                1.10.13
pyOpenSSL               23.2.0
PySocks                 1.7.1
python-dateutil         2.8.2
pytz                    2023.3.post1
PyYAML                  6.0.1
regex                   2023.10.3
requests                2.31.0
ruamel.yaml             0.17.21
safetensors             0.4.0
setuptools              68.0.0
six                     1.16.0
SQLAlchemy              2.0.23
sympy                   1.12
tokenizers              0.15.0
torch                   2.1.1
torchmetrics            0.10.3
tqdm                    4.65.0
transformers            4.35.2
truststore              0.8.0
typing_extensions       4.8.0
tzdata                  2023.3
urllib3                 1.26.18
wheel                   0.41.2
win-inet-pton           1.1.0
zstandard               0.19.0
`

This is the list.

**Comment by guotuofeng** [comment] 2023-11-26 06:17
would you try to install onnxruntime-directml and try again?

**Comment by guotuofeng** [comment] 2023-11-30 08:17
Is it possible you don't switch to the correct conda/virtual envs? from the list, it seems Olive is indeed installed.

**Comment by xiaoyu-work** [comment] 2023-11-30 08:45
I was not able to reproduce this error. Please provide the repro steps if you are still getting this error.

**Comment by xiaoyu-work** [comment] 2023-11-30 10:04
@robgw84 I did follow the steps in the link you mentioned and replaced main branch with a specific olive version:

- conda create --name olive python=3.9
- conda activate olive
- pip install git+https://github.com/microsoft/Olive
- git clone https://github.com/microsoft/olive
- cd olive\examples\directml\stable_diffusion
- pip install -r requirements.txt
- pip install pydantic==1.10.12
- python stable_diffusion.py --optimize

And the above steps work for me. Any difference for your steps?

**Comment by guotuofeng** [comment] 2023-11-30 11:00
> > Is it possible you don't switch to the correct conda/virtual envs? from the list, it seems Olive is indeed installed.
> 
> It's definitely in the envs cause the Miniconda window switches to say (olive) at the start of the line when it's switched to it when you use the Activate command.

You could try to uninstall the olive packages and reinstall it again. If it still doesn't work, the most possibilities is that the conda environment is polluted. You can check the related env folder and check the installation of Olive.

**Comment by guotuofeng** [comment] 2023-12-04 08:55
are there any updates?

**Comment by guotuofeng** [comment] 2023-12-19 12:34
close the issue since there is no any updates

**Closed by guotuofeng** 2023-12-19 12:34 UTC
Labels: bug
